---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: このソリューションは、 NetAppストレージにHyper-Vを導入するために必要な手順を提供します。 
---
= ONTAPストレージ システムを使用した Microsoft Hyper-V の導入について学習します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Microsoft によるコンピュータ仮想化は、Windows Server の Hyper-V の役割を通じて有効になります。  ONTAPストレージ システムと Windows Server 機能を使用して仮想化コンピューティング環境を作成および管理する方法を学習します。

Windows Server プラットフォームは、Hyper-V の役割を使用して仮想化テクノロジを提供します。  Hyper-V は、Windows Server で提供される多くのオプションの役割の 1 つです。



== 概要

Hyper-V の役割により、Windows Server に組み込まれた仮想化テクノロジを使用して、仮想化されたコンピューティング環境を作成および管理できます。  Hyper-V テクノロジーは、ハードウェアを仮想化して、1 台の物理コンピューター上で複数のオペレーティング システムを同時に実行できる環境を提供します。 Hyper-V を使用すると、仮想マシンとそのリソースを作成および管理できます。各仮想マシンは、独自のオペレーティング システムを実行できる、分離された仮想化されたコンピュータ システムです。  Hyper-V は、効率性の向上とコストの削減を目的としたさまざまなビジネス目標をサポートするアプリケーションとワークロードを仮想化するインフラストラクチャを提供します。これは、特に現在の市場状況において組織が複数のハイパーバイザーの共存を求めている場合に、VMware vSphere の完璧な代替手段となります。



== 観客

このドキュメントでは、 NetApp ONTAPシステムを使用した Hyper-V クラスター構成のアーキテクチャと展開手順について説明します。このドキュメントの対象読者には、セールス エンジニア、フィールド コンサルタント、プロフェッショナル サービス、IT マネージャー、パートナー エンジニア、および Hyper-V をプライマリまたは代替ハイパーバイザーとして展開したい顧客が含まれます。



== アーキテクチャ

このドキュメントで説明されているアーキテクチャには、具体的には Microsoft Windows Server 2022 と Hyper-V 仮想化が含まれます。 NetApp は、あらゆる導入の一部として仮想化ソフトウェアとインフラストラクチャ管理ソフトウェアを強く推奨しています。構成では、各コンポーネントのベスト プラクティスを使用して、信頼性の高いエンタープライズ クラスのインフラストラクチャを実現します。



== ユースケースの概要

このドキュメントでは、 NetAppオールフラッシュFASおよびASAアレイ モデルを使用して、Microsoft Windows Server 2022 上のワークロードとして最適に動作するように Hyper-V クラスターを設定するための展開手順とベスト プラクティスについて説明します。サーバーのオペレーティング システム/ハイパーバイザーは Microsoft Windows Server 2022 です。このガイダンスは、ストレージ エリア ネットワーク (SAN) およびネットワーク接続ストレージ (NAS) プロトコルを介してデータを提供するNetAppストレージ システムを対象としています。
