---
sidebar: sidebar 
permalink: migration/migrate-vms-to-ec2-fsxn-overview.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: 'この技術レポートでは、Cirrus Migrate Cloud (CMC) の MigrateOps の「コードとしてのデータモビリティ」機能を使用して、オンプレミスの VMware vSphere VM を、FSx ONTAP iSCSI LUN 上にデータディスクが配置された Amazon EC2 インスタンスに移行する方法について説明します。' 
---
= Amazon FSx for ONTAPを使用して VM を Amazon EC2 に移行する方法について学習します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Amazon FSx for NetApp ONTAP を使用すると、スナップショット、シンプロビジョニング、レプリケーションなどの重要なストレージ機能を維持しながら、VMware vSphere VM を Amazon EC2 に簡単に移行できます。使い慣れたツールとプロトコルをサポートし、移行プロセスを簡素化し、コストと複雑さを軽減します。

組織は、Amazon Elastic Compute Cloud (Amazon EC2) インスタンスやAmazon FSx for NetApp ONTAP (FSx ONTAP) などのサービスを活用して、IT インフラストラクチャを最新化し、コストを削減し、運用効率を向上させながら、AWS 上のクラウドコンピューティング ソリューションへの移行を加速しています。これらの AWS サービスにより、消費ベースの価格設定モデル、エンタープライズストレージ機能を通じて総所有コスト (TCO) を最適化する移行が可能になり、進化するグローバルなビジネス需要に対応できる柔軟性と拡張性が提供されます。



== 概要

VMware vSphere に多大な投資をしている企業にとって、現在の市場状況を考慮すると、AWS への移行はコスト効率の高い選択肢であり、またとないチャンスとなります。

これらの組織は、AWS に移行する際、特にストレージに関しては使い慣れた機能セットを維持しながら、クラウドの俊敏性とコストのメリットを活用しようとしています。ワークロードを移行したり、災害復旧ソリューションを設定したりする場合、使い慣れたストレージ プロトコル (特に iSCSI) のプロセス、ツール、スキルセットを使用してシームレスな操作を維持することが重要です。

AWS マネージドストレージサービス FSx ONTAPを使用して、オンプレミスのサードパーティベンダーのストレージから取得したエンタープライズストレージ機能を保持することで、企業は AWS のパワーを最大化し、中断を最小限に抑え、将来の投資を最大限に活用できます。

この技術レポートでは、Cirrus Migrate Cloud (CMC) の MigrateOps「コードとしてのデータモビリティ」機能を使用して、オンプレミスの VMware vSphere VM を、FSx ONTAP iSCSI LUN 上にデータディスクが配置された Amazon EC2 インスタンスに移行する方法について説明します。



== ソリューション要件

VMware のお客様が現在解決しようとしている課題は数多くあります。これらの組織は次のことを望んでいます。

. シン プロビジョニング、ストレージ効率テクノロジー、ゼロ フットプリント クローン、統合バックアップ、ブロック レベルのレプリケーション、階層化などのエンタープライズ ストレージ機能を活用します。これにより、初日から AWS への移行作業を最適化し、将来を見据えた展開が可能になります。
. FSx ONTAPとそれが提供するコスト最適化機能を組み込むことで、現在 AWS 上で Amazon EC2 インスタンスを使用しているストレージ展開を最適化します。
. 必要な IOPS とスループットのパラメータを満たすように Amazon EC2 インスタンスのサイズを適切に調整することで、ブロックストレージソリューションで Amazon EC2 インスタンスを使用する際の総所有コスト (TCO) を削減します。ブロックストレージでは、Amazon EC2 ディスク操作の帯域幅と I/O レートに上限が設けられています。 FSx ONTAPを使用したファイル ストレージでは、ネットワーク帯域幅が使用されます。つまり、FSx ONTAPには VM レベルの I/O 制限はありません。




== 技術コンポーネントの概要



=== FSx ONTAP の概念

Amazon FSx ONTAP は、 NetApp ONTAPファイルシステムに AWS 上の使い慣れたONTAPデータ管理機能、パフォーマンス、API をすべて提供する、完全に管理された AWS ストレージサービスです。高性能ストレージは複数のプロトコル (NFS、SMB、iSCSI) をサポートし、Windows、Linux、macOS EC2 インスタンスを使用するワークロードに単一のサービスを提供します。

FSx ONTAP はONTAPファイル システムであるため、 SnapMirrorデータ レプリケーション テクノロジー、シン クローン、 NetApp Snapshot コピーなど、使い慣れたNetApp の機能とサービスが多数備わっています。データ階層化による低コストの容量層を活用することで、FSx ONTAP は弾力性を高め、事実上無制限の規模を実現できます。さらに、 NetApp独自のストレージ効率テクノロジーにより、AWS でのストレージ コストがさらに削減されます。詳細については、link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx ONTAPを使い始める"] 。



==== ファイルシステム

FSx ONTAPの中心的なリソースは、ソリッド ステート ドライブ (SSD) ストレージに基づくファイル システムです。  FSx ONTAPファイルシステムをプロビジョニングする場合、ユーザーは必要なスループットとストレージ容量を入力し、ファイルシステムが配置される Amazon VPC を選択します。

ユーザーは、ファイル システムの 2 つの組み込み高可用性展開モデル (マルチ アベイラビリティ ゾーン (AZ) 展開またはシングル AZ 展開) から選択することもできます。これらの各オプションは独自のレベルの耐久性と可用性を提供し、お客様はユースケースのビジネス継続性要件に応じて選択できます。マルチ AZ デプロイメントは、2 つの AZ 間でシームレスにレプリケートするデュアルノードで構成されます。よりコストが最適化された単一 AZ デプロイメント オプションでは、ファイル システムが 2 つのノードに構造化され、両方とも単一の AZ 内に存在する 2 つの別々の障害ドメインに分割されます。



=== Storage Virtual Machine

FSx ONTAPファイル システム内のデータは、ストレージ仮想マシン (SVM) と呼ばれる論理ストレージ パーティションを介してアクセスされます。  SVM は、実際には独自のデータおよび管理アクセス ポイントを備えた独自のファイル サーバーです。  FSx ONTAPファイルシステム上の iSCSI LUN にアクセスする場合、Amazon EC2 インスタンスは SVM の iSCSI エンドポイント IP アドレスを使用して SVM と直接インターフェースします。

クラスター内で単一の SVM を維持することは可能ですが、クラスター内で複数の SVM を実行するオプションには、幅広い用途と利点があります。お客様は、ワークロード分離の要件などのビジネス ニーズを考慮して、構成する SVM の最適な数を決定できます。



==== ボリューム

FSx ONTAP SVM 内のデータは、仮想コンテナとして機能するボリュームと呼ばれる構造に保存され、整理されます。個々のボリュームは、単一または複数の LUN で構成できます。各ボリュームに保存されるデータは、ファイル システムのストレージ容量を消費します。ただし、FSx ONTAP はボリュームをシンプロビジョニングするため、ボリュームは保存されるデータの量分のストレージ容量のみを占有します。



=== Cirrus Migrate Cloud MigrateOpsのコンセプト

CMC は、Cirrus Data Solutions, Inc. が提供する取引可能な SaaS (Software-as-a-Service) サービスであり、AWS Marketplace から入手できます。  MigrateOps は、CMC の Data-Mobility-as-Code 自動化機能であり、YAML のシンプルな操作構成を使用して、大規模なデータ移動操作を宣言的に管理できます。  MigrateOps 構成では、データ移動タスクを実行する方法を決定します。  MigrateOpsの詳細については、以下を参照してください。link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["MigrateOpsについて"] 。

MigrateOps は、プロセス全体を合理化することを目的として構築された自動化ファーストのアプローチを採用しており、運用を中断することなくクラウド規模のエンタープライズ データのモビリティを保証します。  CMC が自動化のために提供する豊富な機能に加えて、MigrateOps は次のような、外部で管理されることが多いその他の自動化も追加します。

* OSの修復
* アプリケーションの切り替えと承認のスケジュール
* ゼロダウンタイムのクラスタ移行
* パブリック/プライベートクラウドプラットフォームの統合
* 仮想化プラットフォームの統合
* エンタープライズストレージ管理統合
* SAN（iSCSI）構成


上記のタスクが完全に自動化されているため、オンプレミスのソース VM の準備 (AWS エージェントやツールの追加など)、宛先 FSx LUN の作成、AWS 宛先インスタンスでの iSCSI およびマルチパス/MPIO の設定、アプリケーション サービスの停止/開始のすべてのタスクなどの面倒な手順が、YAML ファイルでパラメータを指定するだけで排除されます。

FSx ONTAPは、組織がオンプレミス環境で以前に使用していたすべての機能を提供しながら、データ LUN を提供し、Amazon EC2 インスタンスタイプを適切なサイズにするために使用されます。  CMC の MigrateOps 機能は、マップされた iSCSI LUN のプロビジョニングを含むすべての手順を自動化し、予測可能な宣言的な操作に変換するために使用されます。

*注*: CMC では、ストレージ ソース ストレージから FSx ONTAPへの安全なデータ転送を確保するために、ソースおよび宛先の仮想マシン インスタンスに非常に薄いエージェントがインストールされている必要があります。



== Amazon FSx ONTAP をEC2 インスタンスで使用するメリット

Amazon EC2 インスタンス用の FSx ONTAPストレージには、次のようないくつかの利点があります。

* 最も要求の厳しいワークロードに対して一貫した高いパフォーマンスを提供する、高スループットと低レイテンシのストレージ
* インテリジェントNVMeキャッシュによりパフォーマンスが向上
* 調整可能な容量、スループット、および IOP をオンザフライで変更でき、変化するストレージ需要に迅速に適応できます。
* オンプレミスのONTAPストレージから AWS へのブロックベースのデータレプリケーション
* オンプレミスの VMware 展開で広く使用されている iSCSI を含む、マルチプロトコルのアクセシビリティ
* NetApp SnapshotテクノロジーとSnapMirrorによってオーケストレーションされたDRは、データ損失を防ぎ、リカバリを高速化します。
* シンプロビジョニング、データ重複排除、圧縮、コンパクションなど、ストレージのフットプリントとコストを削減するストレージ効率機能
* 効率的なレプリケーションにより、バックアップの作成にかかる時間が数時間から数分に短縮され、RTOが最適化されます。
* NetApp SnapCenterを使用したファイルのバックアップとリストアの詳細なオプション


iSCSI ベースのストレージレイヤーとして FSx ONTAPを使用して Amazon EC2 インスタンスを導入すると、高パフォーマンス、ミッションクリティカルなデータ管理機能、コスト削減を実現するストレージ効率機能が得られ、AWS での導入を変革できます。

フラッシュ キャッシュ、複数の iSCSI セッションを実行し、5% のワーキング セット サイズを活用することで、FSx ONTAPは ~350K の IOPS を実現し、最も集中的なワークロードにも対応できるパフォーマンス レベルを実現できます。

FSx ONTAPにはブロックストレージ帯域幅の制限ではなく、ネットワーク帯域幅の制限のみが適用されるため、ユーザーは小さな Amazon EC2 インスタンスタイプを活用しながら、はるかに大きなインスタンスタイプと同じパフォーマンス率を実現できます。このような小さなインスタンス タイプを使用すると、コンピューティング コストも低く抑えられ、TCO も最適化されます。

FSx ONTAPが複数のプロトコルに対応できることは、もう 1 つの利点であり、既存のさまざまなデータおよびファイル サービスの要件に合わせて単一の AWS ストレージ サービスを標準化するのに役立ちます。  VMware vSphere に多大な投資をしている企業にとって、現在の市場状況を考慮すると、AWS への移行はコスト効率の高い選択肢であり、またとないチャンスとなります。
