---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'NAS プロトコル (NFS、SMB) と SAN プロトコル (FC、iSCSI、NVMe) を使用して、Proxmox 仮想環境 (VE) 用のONTAPストレージをプロビジョニングします。Proxmox VE クラスターの共有ストレージを構成するには、適切なプロトコル固有の手順を選択します。' 
---
= NetApp ONTAPを使用した Proxmox VE のストレージ プロトコルについて学習します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NAS プロトコル (NFS、SMB) と SAN プロトコル (FC、iSCSI、NVMe) を使用して、Proxmox 仮想環境 (VE) 用のONTAPストレージをプロビジョニングします。Proxmox VE クラスターの共有ストレージを構成するには、適切なプロトコル固有の手順を選択します。

Proxmox VE ホストに、 ONTAP論理インターフェイスと通信するスイッチにケーブル接続された FC、イーサネット、またはその他のサポートされているインターフェイスがあることを確認します。常にチェックしてください https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"] サポートされている構成の場合。サンプルシナリオは、各 Proxmox VE ホストに 2 つの高速ネットワーク インターフェイス カードが用意されており、それらが相互に接続されてフォールト トレランスとパフォーマンスのための結合インターフェイスが作成されていることを前提として作成されています。ホスト管理、VM/コンテナ トラフィック、ストレージ アクセスを含むすべてのネットワーク トラフィックに同じアップリンク接続が使用されます。より多くのネットワーク インターフェイスが使用可能な場合は、ストレージ トラフィックを他の種類のトラフィックから分離することを検討してください。

ONTAPストレージ アーキテクチャとサポートされているストレージタイプの詳細については、以下を参照してください。 link:proxmox-ontap-architecture.html["Proxmox VE のONTAPストレージ アーキテクチャについて学ぶ"] そして link:proxmox-storage-types.html["Proxmox VE でサポートされているストレージタイプについて学ぶ"]。


NOTE: SAN プロトコル (FC、iSCSI、NVMe-oF) で LVM を使用する場合、ボリューム グループには複数の LUN または NVMe 名前空間を含めることができます。その場合、データの整合性を確保するために、すべての LUN または名前空間が同じ整合性グループの一部である必要があります。複数のONTAP SVM にまたがるボリューム グループはサポートされていません。各ボリューム グループは、同じ SVM の LUN または名前空間から作成する必要があります。



== ストレージ プロトコルを選択する

環境と要件に一致するプロトコルを選択します。

* link:proxmox-ontap-smb.html["SMB/CIFSストレージを構成する"] - マルチチャネル サポートを使用して Proxmox VE の SMB/CIFS ファイル共有を構成し、複数のネットワーク接続でのフォールト トレランスとパフォーマンスの向上を実現します。
* link:proxmox-ontap-nfs.html["NFSストレージの設定"] - 複数のネットワーク接続を使用してフォールト トレランスとパフォーマンス強化を実現するには、nConnect またはセッション トトランキングを使用して Proxmox VE の NFS ストレージを構成します。
* link:proxmox-ontap-fc.html["FCでLVMを構成する"] - Proxmox VE ホスト間でハイパフォーマンス、低レイテンシのブロックストレージ アクセスを実現するために、ファイバー チャネルを使用して論理ボリューム マネージャー (LVM) を構成します。
* link:proxmox-ontap-iscsi.html["iSCSIでLVMを構成する"] - マルチパスをサポートする標準イーサネット ネットワーク経由でブロックストレージ アクセスように、iSCSI を使用して論理ボリューム マネージャー (LVM) を構成します。
* link:proxmox-ontap-nvme-fc.html["NVMe/FC で LVM を構成する"] - 最新の NVMe プロトコルを使用してハイパフォーマンスブロック ストレージを実現するために、NVMe over Fibre Channel で論理ボリューム マネージャー (LVM) を構成します。
* link:proxmox-ontap-nvme-tcp.html["NVMe/TCP で LVM を構成する"] - 最新の NVMe プロトコルを使用して、標準イーサネット ネットワーク上でハイパフォーマンスブロック ストレージを実現するために、NVMe over TCP で論理ボリューム マネージャー (LVM) を構成します。

