---
sidebar: sidebar 
permalink: proxmox/proxmox-deploy-guidelines.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, nvme, fc, ontap, storage, aff, asa, virtual machines, vm, containers, proxmox backup server 
summary: 'Proxmox Virtual Environment (VE) はNetApp ONTAPストレージと統合され、仮想マシンとコンテナ用の共有ストレージを提供し、ライブ マイグレーションの高速化、テンプレートの一貫性、集中バックアップを可能にします。ONTAPストレージ システムを使用して Proxmox VE クラスターを導入および最適化するためのアーキテクチャ、ネットワークとストレージの構成、ベスト プラクティスについて学習します。' 
---
= NetApp ONTAPストレージを使用したProxmox仮想環境の導入ガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Proxmox Virtual Environment (VE) はNetApp ONTAPストレージと統合され、仮想マシンとコンテナ用の共有ストレージを提供し、ライブ マイグレーションの高速化、テンプレートの一貫性、集中バックアップを可能にします。ONTAPストレージ システムを使用して Proxmox VE クラスターを導入および最適化するためのネットワークおよびストレージ構成のガイドラインとベスト プラクティスについて学習します。

サポートされているストレージの種類とコンテンツの互換性については、以下を参照してください。 link:proxmox-storage-types.html["Proxmox VE でサポートされているストレージタイプについて学ぶ"]。



== ネットワーク構成ガイドライン

ネットワークのパフォーマンスと信頼性を最適化するには、次のガイドラインに従ってください。

* Proxmox VE ノードとONTAPストレージ間の二重冗長ネットワーク パスを確保します。
* 帯域幅とフォールト トレランスを向上させるには、リンク アグリゲーション (LACP) を使用します。
* スパニング ツリーの問題を回避するようにネットワーク トポロジを設計します。必要に応じて、RSTP や MSTP などの機能を使用します。
* VLAN を実装して、さまざまな種類のトラフィックをセグメント化し、セキュリティを強化します。
* ストレージ トラフィックのパフォーマンスを向上させるには、すべてのネットワーク デバイスでジャンボ フレーム (MTU 9000) を構成します。
* VLAN ゾーンが構成されている場合は、Linux ブリッジ経由の Open vSwitch (OVS) の使用を検討してください。




== ストレージ構成のベストプラクティス

ストレージのパフォーマンスとスケーラビリティを最適化するには、次のベスト プラクティスに従ってください。

* スナップショットやクローン作成などの ONTAP の高度なデータ管理機能を使用して、データ保護とリカバリを強化します。
* 大容量が必要な場合は、 FlexGroupボリュームを使用して、 ONTAPのスケーラビリティを最大限に活用してください。
* 地理的に分散した環境では、 FlexCacheを使用してイメージとテンプレートを Proxmox VE ノードの近くに配布し、展開時間を短縮して集中管理できるようにします。
* FlexGroup をNFS と併用する場合は、nConnect またはセッショントランキングと pNFS を組み合わせて使用​​し、パフォーマンスと可用性を最適化します。
* ブロック プロトコルの場合、適切なゾーニングとLUNマスキングを確保して、許可された Proxmox VE ノードのみへのアクセスを制限します。
* VM の増加とデータのニーズに対応するために十分なストレージ容量を割り当てます。
* ストレージ階層化を実装して、パフォーマンスとコスト効率を最適化します。
* NetApp管理ツールを使用して、ストレージのパフォーマンスと健全性を定期的に監視します。
* NetApp Consoleを使用して、複数のONTAPシステムを集中管理します。
* ランサムウェア攻撃から保護するために、 ONTAPでランサムウェア保護機能を有効にします。




== Proxmox VE 設定ガイドライン

NetApp ONTAPストレージを使用して Proxmox VE を最適化するには、次のガイドラインに従ってください。

* 最新の機能とバグ修正の恩恵を受けるには、Proxmox VE を最新の安定バージョンに更新してください。
* VM ストレージにNetApp ONTAPの共有ストレージを使用するように Proxmox VE を構成します。
* Proxmox VE クラスターをセットアップして、VM の高可用性とライブ マイグレーションを有効にします。
* クラスター通信には冗長ネットワークを使用し、そのうち 1 つをライブ マイグレーション専用にします。
* 競合を防ぐため、クラスター間で同じ VM またはコンテナ ID を再利用しないでください。
* VM のパフォーマンスと機能を向上させるには、VirtIO SCSI シングル コントローラーを使用します。
* IO 要求の高い VM に対して IO スレッド オプションを有効にします。
* VM ディスクで破棄/TRIM サポートを有効にして、ストレージの使用を最適化します。

