---
sidebar: sidebar 
permalink: euc/euc-overview.html 
keywords: euc, digital workspace, virtual desktop, vdi, virtual desktop infrastructure, cloud desktop, virtual application, application virtualization, app virtualization, virtual desktop management, desktop management, application management 
summary:  
---
= NetAppを使用したエンドユーザコンピューティングについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
End User Computing（EUC）は、ユーザーがあらゆるデバイスから、どこからでも自分のデスクトップとアプリケーションにアクセスできるようにするテクノロジです。NetAppのEUCソリューションには、仮想デスクトップ インフラ（VDI）、アプリケーション仮想化、およびユーザ プロファイル管理が含まれます。NetAppのEUCソリューションを使用することで、組織はエンドユーザの生産性を向上させ、コストを削減し、セキュリティを強化できます。



== エンドユーザコンピューティング（EUC）とは

End User Computing（EUC）は、ユーザーがあらゆるデバイスから、どこからでも自分のデスクトップとアプリケーションにアクセスできるようにするテクノロジです。EUCソリューションには通常、仮想デスクトップ インフラ（VDI）、アプリケーション仮想化、およびユーザープロファイル管理ツールが含まれます。EUCを使用することで、組織は生産性の向上、コスト削減、エンドユーザのセキュリティ強化を実現できます。ファイル共有とホームディレクトリもEUCソリューションの一部であり、ユーザーはあらゆるデバイスから自分のファイルやデータにアクセスできます。

ユーザは、単一のアプリケーションまたはフルデスクトップを介して、作業を実行するためにアプリケーションにアクセスする必要があります。一部のユーザは、デスクトップワークフローまたは特定のアプリケーションのユースケースに対して、ハイエンドのグラフィックスアプリケーションを必要とする場合があります。NetAppを使用したEUCソリューションは、各ユーザのニーズと要件に基づいて、適切なソリューションを提供できます。NetAppのEUCソリューションにより、組織はユーザに対して、あらゆるデバイスから、あらゆる場所でデスクトップとアプリケーションへのアクセスを提供できると同時に、データが安全かつ効率的に保存されることを保証します。

組織は、EUCソリューションをオンプレミス、クラウド、またはハイブリッド環境に導入することを選択でき、ニーズに最適な導入モデルを選択できる柔軟性を提供します。NetAppのEUCソリューションを利用することで、組織は生産性の向上、コスト削減、エンドユーザのセキュリティ強化を実現できるだけでなく、ユーザがどこからでも柔軟に仕事ができる環境を提供することができます。



== NetAppを使用したエンドユーザコンピューティングの高レベルのメリット

NetAppのEUCソリューションは、組織に以下のようないくつかのメリットをもたらします。* 生産性の向上：EUCを使用すると、ユーザーはあらゆるデバイスから、どこからでもデスクトップやアプリケーションにアクセスでき、生産性とコラボレーションを向上させることができます。* コスト削減：EUCは、デスクトップとアプリケーション管理を一元化することで、組織のコスト削減に役立ち、高価なハードウェアやソフトウェアの必要性を軽減できます。* セキュリティの強化：EUCは、デスクトップとアプリケーション管理を一元化することで、組織のセキュリティを強化でき、データ漏洩やその他のセキュリティインシデントのリスクを軽減できます。* 拡張性：NetAppのEUCソリューションは拡張性を考慮して設計されており、組織は必要に応じてユーザーを簡単に追加または削除できます。* 柔軟性：NetAppのEUCソリューションはオンプレミス、クラウド、またはハイブリッド環境に導入でき、組織がニーズに最適な導入モデルを選択できる柔軟性を提供します。

詳細については、link:euc-benefits.html["エンドユーザコンピューティング向けNetAppストレージのメリット"]ページをご覧ください。



== NetAppのEUCソリューション

NetAppは、以下を含むさまざまなEUCソリューションを提供しています：* 仮想デスクトップ インフラ（VDI）：VDIソリューションにより、組織はエンドユーザに仮想デスクトップを提供し、あらゆるデバイスから、どこからでもデスクトップとアプリケーションにアクセスできるようにします。* アプリケーション仮想化：アプリケーション仮想化ソリューションにより、組織はエンドユーザに仮想アプリケーションを提供し、あらゆるデバイスから、どこからでもアプリケーションにアクセスできるようにします。* ファイル共有とホーム ディレクトリ：ファイル共有とホーム ディレクトリのソリューションにより、組織はユーザがあらゆるデバイスから、どこからでもファイルやデータにアクセスできるようにすると同時に、データが安全かつ効率的に保存されることを保証します。* ユーザ プロファイル管理：ユーザ プロファイル管理ソリューションにより、組織は複数のデバイスにわたってユーザ プロファイルと設定を管理でき、使用するデバイスに関係なく一貫したエクスペリエンスをユーザに提供します。
