---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: NetApp ONTAP NFS データストアを含む vSphere 8 クラスタを VMware Cloud Foundation 管理ドメインに変換するための要件を確認します。 
---
= NFS データストアを使用して vCenter Server インスタンスを VCF 管理ドメインに変換するための展開要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP NFS データストアを含む vSphere 8 クラスタを VMware Cloud Foundation 管理ドメインに変換するための要件を確認します。

変換プロセスには、 AFFまたはASAストレージ システム、FC トラフィック用の SVM と LIF、スイッチ上の NFS ゾーニング、ESXi ホストと vCenter を含む vSphere クラスター、および vMotion 専用のネットワーク セグメントが必要です。



== インフラストラクチャ要件

次のコンポーネントと構成が適切であることを確認してください。

* NFS トラフィックを許可するように構成されたストレージ仮想マシン (SVM) を備えたNetApp AFFストレージ システム。
* NFS トラフィックを伝送するために IP ネットワーク上に作成され、SVM に関連付けられた論理インターフェイス (LIF)。
* 4 台の ESXi ホストと、クラスター上に共存する vCenter アプライアンスを備えた vSphere クラスター。
* この目的のために確立された VLAN またはネットワーク セグメント上の vMotion および NFS ストレージ トラフィック用に構成された分散ポート グループ。
* VCF 変換用のソフトウェア。必要なソフトウェアについては、 https://support.broadcom.com/["Broadcom サポートポータル"] 。
* ONTAPツールの前提条件。
+
ONTAPツールの前提条件の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["ONTAP tools for VMware vSphereの前提条件"] 。

+
ONTAP tools for VMware vSphereは、 HA 構成または非 HA 構成のいずれにもインストールできます。





== その他のリソース

* vSphere を VCF 5.2 に変換またはインポートする際にサポートされるストレージおよびその他の考慮事項については、以下を参照してください。 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/considerations-before-converting-or-importing-existing-vsphere-environments-into-vcf-admin.html["既存の vSphere 環境を VMware Cloud Foundation に変換またはインポートする前に考慮すべき事項"] 。
* ONTAPストレージシステムの設定については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9 ドキュメント"] 。
* VCFの設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 5.2 のドキュメント"] 。




== 次の手順

展開要件を確認した後、link:vmw-vcf-mgmt-nfs-deploy.html["ONTAPツールを導入し、NFSデータストアをプロビジョニングする"] 。
