---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary: 'VMware Cloud Foundation (VCF) は、VCF 管理ドメインと仮想インフラストラクチャ (VI) ワークロード ドメインのストレージを拡張するための幅広い補足ストレージ オプションをサポートしています。' 
---
= 補助ストレージを使用して VCF 環境のストレージを拡張する方法について説明します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) は、VCF 管理ドメインと仮想インフラストラクチャ (VI) ワークロード ドメインのストレージを拡張するための幅広い補足ストレージ オプションをサポートしています。

NetApp のONTAP tools for VMware vSphereは、 NetAppストレージを VCF 環境にシームレスに統合することで、この拡張のための効率的なソリューションを提供します。

ONTAPツールはデータストアのセットアップと管理を簡素化し、管理者が vSphere Client から直接ストレージをプロビジョニングおよび管理できるようにします。スナップショット、クローン作成、データ保護などの ONTAP の高度な機能により、VCF 環境内のストレージ パフォーマンス、効率、スケーラビリティが向上します。



== ストレージ拡張にサポートされているプロトコル

VCF 環境は、それぞれ独自の利点とユースケースを提供する複数のストレージ プロトコルを使用して拡張できます。

次のプロトコルを使用して、VCF 管理ドメインおよび VI ワークロード ドメインのストレージを拡張できます。環境に最適なオプションを選択して、補足ストレージを VCF 展開にシームレスに統合します。

.iSCSI
標準イーサネット ネットワークを使用するブロックベースのプロトコル。高いパフォーマンス、柔軟性、コスト効率の高いスケーリングを必要とする環境に最適です。

iSCSI は VMFS データストアで広く使用されており、スナップショットやクローン作成などの高度なONTAP機能をサポートしています。

* *高性能:* 高速で効率的なデータ転送速度と低遅延を実現する高性能を提供します。要求の厳しいエンタープライズ アプリケーションや仮想化環境に最適です。
* *管理の容易さ:* 使い慣れた IP ベースのツールとプロトコルを使用して、ストレージ管理を簡素化します。
* *コスト効率が高い:* 既存のイーサネット インフラストラクチャを使用するため、特殊なハードウェアの必要性が減り、組織は信頼性が高くスケーラブルなストレージ ソリューションを実現できます。


NetAppストレージシステムでiSCSIを使用する方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html["iSCSI による SAN プロビジョニング"] 。

.Fibre Channel（FC）
専用の FC ネットワークを使用する高速、低遅延のプロトコル。 FC は、信頼性、専用帯域幅、堅牢なエラー修正を必要とするミッションクリティカルなワークロードに適しています。エンタープライズ環境の VMFS データストアでよく使用されます。

* *高性能:* FC は高速データ転送速度を提供するため、大量のデータへの高速かつ信頼性の高いアクセスを必要とするアプリケーションに最適です。
* *低レイテンシ:* 非常に低いレイテンシ。これは、データベースや仮想化環境などのパフォーマンスが重視されるアプリケーションにとって非常に重要です。
* *信頼性:* FC ネットワークは、冗長性やエラー訂正などの機能が組み込まれており、堅牢性と信頼性に優れています。
* *専用帯域幅:* FC はストレージ トラフィックに専用の帯域幅を提供し、ネットワーク輻輳のリスクを軽減します。


NetAppストレージシステムでのファイバーチャネルの使用に関する詳細については、 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["FCを使用したSANプロビジョニング"] 。

.NFS (ネットワーク ファイル システム)
ホスト間でのファイルの簡単な共有と管理を可能にするファイルベースのプロトコル。  NFS はセットアップが簡単で、効率的に拡張できるため、柔軟なファイル アクセスを必要とする仮想化されたワークロードや環境に適しています。

NFS データストアは、管理ドメインとワークロード ドメインの両方でONTAPと vSphere によってサポートされています。

* *シンプルで使いやすい:* NFS はセットアップと管理が簡単なので、迅速かつ簡単なファイル共有を必要とする環境に最適です。
* *スケーラビリティ:* ONTAP のアーキテクチャにより、NFS は効率的に拡張でき、インフラストラクチャに大きな変更を加えることなく増大するデータ ニーズに対応できます。
* *柔軟性:* NFS は幅広いアプリケーションとワークロードをサポートしており、仮想化環境を含むさまざまなユースケースに幅広く対応できます。


詳細については、 link:vmw-vvf-overview.html["vSphere 8 向け NFS v3 リファレンス ガイド"] 。

.NVMe/TCP
TCP/IP を使用した標準イーサネット ネットワーク上で高パフォーマンスと低レイテンシを実現する最新のプロトコルです。  NVMe/TCP は、要求の厳しいアプリケーションや大規模なデータ操作に最適で、特殊なハードウェアを必要とせずにスケーラビリティとコスト効率を実現します。

* *高性能:* 低レイテンシと高データ転送速度で優れたパフォーマンスを実現します。これは、要求の厳しいアプリケーションや大規模なデータ操作にとって非常に重要です。
* *スケーラビリティ:* スケーラブルな構成をサポートし、IT 管理者はデータ要件の増大に応じてインフラストラクチャをシームレスに拡張できます。
* *コスト効率が高い:* 標準のイーサネット スイッチ上で実行され、TCP データグラム内にカプセル化されます。実装に特別な機器は必要ありません。


NVMeの利点の詳細については、以下を参照してください。 https://www.netapp.com/data-storage/nvme/what-is-nvme/["NVME とは何ですか?"] 。



== 補助ストレージを追加するユースケース

次のユースケースでは、さまざまなプロトコルと構成を使用して、VCF 管理ドメインと仮想インフラストラクチャ (VI) ワークロード ドメインに追加のストレージを追加する方法を示します。

* link:vmw-vcf-mgmt-supplemental-iscsi.html["iSCSI による管理ドメイン"]
* link:vmw-vcf-mgmt-supplemental-fc.html["FCによる管理ドメイン"]
* link:vmw-vcf-viwld-supp-iscsi-vvols.html["vVolsを使用した仮想インフラストラクチャ ワークロード ドメイン (iSCSI)"]
* link:vmw-vcf-viwld-supp-nfs-vvols.html["vVolsを使用した仮想インフラストラクチャ ワークロード ドメイン (NFS)"]
* link:vmw-vcf-viwld-supp-nvme.html["NVMe/TCP を使用した仮想インフラストラクチャ ワークロード ドメイン"]
* link:vmw-vcf-viwld-supp-fc.html["FC を使用した仮想インフラストラクチャ ワークロード ドメイン"]

