---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC ベースの VMFS データストアを ONTAP 上で VCF ワークロード ドメインの主要ストレージとして使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このユースケースでは、Fibre Channel (FC) VMFSデータストアをONTAP上にセットアップする手順を概説します。ONTAPは、VMware Cloud Foundation（VCF）ワークロードドメインの主要ストレージソリューションとして使用します。この手順では、必要なコンポーネント、構成手順、および展開プロセスを概説します。



[[benefits-of-fibre-channel]]
== ファイバーチャネルの利点

*高性能:* FC は高速データ転送速度を提供するため、大量のデータへの高速かつ信頼性の高いアクセスを必要とするアプリケーションに最適です。

*低レイテンシ:* 非常に低いレイテンシ。これは、データベースや仮想化環境などのパフォーマンスが重視されるアプリケーションにとって非常に重要です。

*信頼性:* FC ネットワークは、冗長性やエラー訂正などの機能が組み込まれており、堅牢性と信頼性に優れています。

*専用帯域幅:* FC はストレージ トラフィックに専用の帯域幅を提供し、ネットワーク輻輳のリスクを軽減します。

NetAppストレージシステムでのファイバーチャネルの使用に関する詳細については、 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["FCを使用したSANプロビジョニング"] 。



[[scenario-overview]]
== シナリオの概要

このシナリオでは、次の大まかな手順について説明します。

* FC トラフィック用の論理インターフェイス (LIF) を備えたストレージ仮想マシン (SVM) を作成します。
* 展開するホストの WWPN 情報を収集し、 ONTAPストレージ システム上に対応するイニシエーター グループを作成します。
* ONTAPストレージ システムに FC ボリュームを作成します。
* 作成したFCボリュームにイニシエータグループをマッピングします。
* FC スイッチで単一のイニシエーター ターゲット ゾーニングを活用します。イニシエーターごとに 1 つのゾーンを作成します (単一イニシエーター ゾーン)。
+
** 各ゾーンには、SVM のONTAP FC 論理インターフェイス (WWPN) であるターゲットを含めます。 SVM ごとにノードごとに少なくとも 2 つの論理インターフェイスが必要です。物理ポートの WWPN を使用しないでください。


* vCenterでvMotionトラフィック用のネットワーク プールを作成します。
* vCenter のホストをコミッションして、ワークロード ドメインで使用できるようにします。
* プライマリストレージとして VMFS on FC データストアを使用して、VCF Ops にワークロード ドメインをデプロイします。



NOTE: このソリューションは、FCストレージをサポートするONTAPプラットフォーム（NetApp ASAr2、AFF、FASを含む）に適用できます。



[[prerequisites]]
== 前提条件

このシナリオでは、次のコンポーネントと構成が使用されます。

* FCポートがFCスイッチに接続されたONTAP AFF、ASA、またはFASストレージ システム。
* FC lifs で作成された SVM。
* FC スイッチに接続された FC HBA を備えた vSphere。
* FC スイッチには単一のイニシエーター ターゲット ゾーニングが構成されています。
* SVMマルチパスポリシーがアクティブ / アクティブに設定されていることを確認してください。



NOTE: NetApp は、FC LUN にマルチパスを推奨しています。



[[deployment-steps]]
== 展開手順



[[vcf-workload-domain-default-cluster]]
=== VCF Workload Domain - デフォルト クラスター

管理ドメインが稼働状態になったら、VCF ワークロード ドメインを作成できます。

* VCF Ops UI を使用します。vSphere ホストは vCenter にコミッションされ、ネットワークプールが設定されます。System Manager または ONTAP API を使用して、vSphere ホストに LUN をデプロイします。
* 既存のvSphere環境を新しいワークロードドメインとしてインポートします。ONTAP tools for VMware vSphere、System Manager、または ONTAP API を使用して、VMFS データストアをvSphereクラスタにデプロイできます。




[[vcf-workload-domain-additional-cluster]]
=== VCFワークロード ドメイン - 追加クラスター

ワークロードドメインにクラスターを追加するには、 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["SDDCクラスタをVCFドメインに追加する"]を参照してください。

大まかに言うと、ワークロード ドメインに追加のクラスターを追加する手順は次のとおりです。* ホストがコミッショニングされ、ネットワーク プールが vCenter で構成されていることを確認します。* LUN は ONTAP ストレージ システムにプロビジョニングされ、追加クラスター内のホストに提示されます。* vCenter のワークロード ドメインに新しい SDDC クラスターを作成し、ウィザードに従って追加のクラスターをワークロード ドメインに追加します。



[[additional-information]]
== 追加情報

ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation ドキュメント"]を参照してください。
