---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= VMware vSphere 用のSnapCenterプラグインを使用した仮想マシンのバックアップとリストアについて学習します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for VMware vSphereを使用すると、VM、データストア、VMDK ファイルに対して、VM と整合性のある高速なバックアップおよびリストア操作が可能になります。この VMware プラグインはSnapCenter Server と統合され、 SnapCenterアプリケーション固有のプラグインのアプリケーションベースのバックアップとリストアをサポートします。



== ドキュメントリソース

詳細については、次のドキュメント リソースを参照してください。

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphereのドキュメント"]




== ソリューションリソース

SnapCenter Plug-in for VMware vSphereと、VM 用のBlueXP backup and recoveryを備えた次の 3-2-1 バックアップ ソリューションを参照してください。

技術レポート:link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html["SnapCenterプラグインとBlueXP backup and recoveryによる VMware の 3-2-1 データ保護"^]

Tech ONTAPブログ:link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["SnapCenterプラグインとBlueXP backup and recoveryによる VMware の 3-2-1 データ保護"]



== ビデオリソース

.SnapCenter Plug-in for VMware vSphere- ソリューションの前提条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere- 導入
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere- バックアップ ワークフロー
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere- リストアワークフロー
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - SQL リストアワークフロー
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]