---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= ONTAP上のFCベースのVMFSデータストアをVCF管理ドメインの主ストレージとして使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このユースケースでは、VMware Cloud Foundation（VCF）管理ドメインのプライマリストレージとして、ONTAP上にFCベースのVMFSデータストアを作成する手順を概説します。この手順では、必要なコンポーネント、構成、および展開手順の概要を説明します。



[[introduction]]
== はじめに

必要に応じて、vCenterで実行する必要がある手順については外部ドキュメントを参照し、ストレージ構成部分に特有の手順については該当箇所を参照してください。

既存の VMFS データストア（iSCSI および NVMe-oF を含む）を ONTAP を使用して vSphere 環境で変換する方法については、link:vmw-vcf-mgmt-vmfs.html["vSphere環境（VMFSデータストア）をVCF管理ドメインに収束させる"]を参照してください。


NOTE: VCF リリース 5.2 では、既存のvSphere 8 環境を VCF 管理ドメインに変換するか、VCF VI ワークロード ドメインとしてインポートする機能が導入されました。今回のリリース以前は、VCF 管理ドメインのプリンシパル ストレージとして利用できるのは VMware vSAN のみでした。NSX コントローラー VM は、FC ベースの VMFS データストアにデプロイするか、デュアル ネットワーク スイッチを使用して単一障害点を回避することをお勧めします。これらのオプションが利用できない場合は、vSAN を使用してそれらの VM をホストすることを検討してください。


NOTE: このソリューションは、 NetApp ASA、 AFF 、 FASなどの FC ストレージをサポートするONTAPプラットフォームに適用できます。



[[prerequisites]]
== 前提条件

このシナリオでは、次のコンポーネントと構成が使用されます。

* FC トラフィックを許可するように構成されたストレージ仮想マシン (SVM) を備えたNetAppストレージ システム。
* FC トラフィックを伝送し、SVM に関連付けられた FC ファブリック上に論理インターフェイス (LIF) が作成されています。
* ゾーニングは、ホスト HBA およびストレージ ターゲットの FC スイッチ上で単一のイニシエーター ターゲット ゾーニングを使用するように構成されています。


ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation ドキュメント"]を参照してください。



[[deployment-steps]]
== 展開手順



[[management-domain-default-cluster]]
=== 管理ドメイン - デフォルトクラスタ

VCFインストーラーツールは、管理ドメインにおいて、FC上のVMFS、NFS v3、およびvSANデータストアをサポートします。以下の手順では、ONTAPをプリンシパルストレージとして、FCベースのVMFSデータストアを使用して管理ドメインをデプロイする手順を説明します。

既存のvSphere環境の使用の詳細については、link:vmw-vcf-mgmt-vmfs.html["vSphere環境（VMFSデータストア）をVCF管理ドメインに収束させる"]を参照してください。



[[management-domain-additional-cluster]]
=== 管理ドメイン - 追加クラスター

管理ドメインにクラスターを追加するには、 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["SDDCクラスタをVCFドメインに追加する"]を参照してください。

大まかに言うと、管理ドメインに追加のクラスターを追加する手順は次のとおりです。* ホストがコミッショニングされ、ネットワーク プールが vCenter で構成されていることを確認します。* LUN は ONTAP ストレージ システムにプロビジョニングされ、追加クラスター内のホストに提示されます。* vCenter の管理ドメインで新しい SDDC クラスターを作成し、ウィザードに従って追加のクラスターを管理ドメインに追加します。



[[additional-information]]
== 追加情報

ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation ドキュメント"]を参照してください。
