---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-supp-nfs-vvols-network.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, vvol, vvols, array, ontap tools, otv, sddc 
summary: VMware Cloud Foundation 管理ドメイン内の ESXi ホストで NFS ネットワークを構成して、 ONTAPストレージ システムへの接続を有効にします。  VLAN 分離による分散ポート グループを作成し、冗長性のためにアップリンク チーミングを構成し、各 ESXi ホストに VMkernel アダプタを設定して、フェイルオーバー機能用の専用 NFS パスを確立します。 
---
= VCF VIワークロードドメイン内のESXiホスト上のNFSネットワークを構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation 管理ドメイン内の ESXi ホストで NFS ネットワークを構成して、 ONTAPストレージ システムへの接続を有効にします。  VLAN 分離による分散ポート グループを作成し、冗長性のためにアップリンク チーミングを構成し、各 ESXi ホストに VMkernel アダプタを設定して、フェイルオーバー機能用の専用 NFS パスを確立します。

vSphere クライアントを使用して、VI ワークロード ドメイン クラスタで次の手順を実行します。この場合、vCenter Single Sign-On が使用されているため、vSphere クライアントは管理ドメインとワークロード ドメイン全体で共通になります。



== ステップ1: NFSトラフィック用の分散ポートグループを作成する

NFS トラフィックを伝送するネットワークの新しい分散ポート グループを作成するには、次の手順を実行します。

.手順
. vSphere クライアントから、ワークロード ドメインの *インベントリ > ネットワーク* に移動します。既存の分散スイッチに移動し、*新しい分散ポート グループ...*を作成するアクションを選択します。
. *新しい分散ポート グループ* ウィザードで、新しいポート グループの名前を入力し、*次へ* をクリックして続行します。
. *設定の構成*ページで、すべての設定を入力します。VLAN が使用されている場合は、正しい VLAN ID を必ず指定してください。続行するには、[次へ] をクリックします。
. *完了準備完了*ページで変更を確認し、*完了*をクリックして新しい分散ポート グループを作成します。
. ポート グループが作成されたら、ポート グループに移動し、[設定の編集...] アクションを選択します。
. *分散ポート グループ - 設定の編集* ページで、左側のメニューの *チーミングとフェールオーバー* に移動します。NFS トラフィックに使用するアップリンクのチーミングを有効にするには、それらが *アクティブ アップリンク* 領域にまとめられていることを確認します。使用されていないアップリンクを「*未使用のアップリンク*」に移動します。
. クラスタ内の各 ESXi ホストに対してこのプロセスを繰り返します。




== ステップ2: 各ESXiホストにVMkernelアダプタを作成する

ワークロード ドメイン内の各 ESXi ホストに VMkernel アダプタを作成します。

.手順
. vSphere クライアントから、ワークロード ドメイン インベントリ内の ESXi ホストの 1 つに移動します。*構成*タブから*VMkernelアダプタ*を選択し、*ネットワークの追加...*をクリックして開始します。
. *接続タイプの選択* ウィンドウで、*VMkernel ネットワーク アダプタ* を選択し、*次へ* をクリックして続行します。
. *ターゲット デバイスの選択* ページで、以前に作成した NFS の分散ポート グループの 1 つを選択します。
. *ポートのプロパティ*ページで、デフォルト（有効なサービスなし）のままにして、*次へ*をクリックして続行します。
. *IPv4 設定* ページで、*IP アドレス*、*サブネット マスク* を入力し、新しいゲートウェイ IP アドレスを指定します (必要な場合のみ)。続行するには、[次へ] をクリックします。
. *完了準備完了*ページで選択内容を確認し、*完了*をクリックして VMkernel アダプタを作成します。




== 次の手順

ワークロードドメイン内のすべてのESXiホストでNFSのネットワークを構成した後、link:vmw-vcf-viwld-supp-nfs-vvols-storage.html["NFS vVolsのストレージを構成する"] 。
