---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= ONTAP上のFCベースのVMFSデータストアをVCF管理ドメインの主ストレージとして使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このユースケースでは、 ONTAP上の既存の FC ベースの VMFS データストアを VMware Cloud Foundation (VCF) 管理ドメインのプライマリ ストレージとして使用する手順について説明します。この手順では、必要なコンポーネント、構成、および展開手順をまとめています。



== はじめに

必要に応じて、VCF の SDDC マネージャーで実行する必要がある手順については外部ドキュメントを参照し、ストレージ構成部分に固有の手順を参照します。

既存のFCベースのvSphere環境をONTAPに変換する方法については、以下を参照してください。link:vmw-vcf-mgmt-fc.html["vSphere 環境 (FC データストア) を VCF 管理ドメインに変換する"] 。


NOTE: VCF リリース 5.2 では、既存の vSphere 8 環境を VCF 管理ドメインに変換したり、VCF VI ワークロード ドメインとしてインポートしたりする機能が導入されました。このリリースより前は、VMware vSAN が VCF 管理ドメインの主要ストレージの唯一のオプションでした。


NOTE: このソリューションは、 NetApp ASA、 AFF 、 FASなどの FC ストレージをサポートするONTAPプラットフォームに適用できます。



== 前提条件

このシナリオでは、次のコンポーネントと構成が使用されます。

* FC トラフィックを許可するように構成されたストレージ仮想マシン (SVM) を備えたNetAppストレージ システム。
* FC トラフィックを伝送し、SVM に関連付けられた FC ファブリック上に論理インターフェイス (LIF) が作成されています。
* ゾーニングは、ホスト HBA およびストレージ ターゲットの FC スイッチ上で単一のイニシエーター ターゲット ゾーニングを使用するように構成されています。


ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCFの設定方法については、以下を参照してください。link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation ドキュメント"] 。



== 展開手順



=== 管理ドメイン - デフォルトクラスタ

初期クラスター上の FC プリンシパル ストレージは、VCF ブラウンフィールド インポート ツールでのみサポートされます。  VCF が Cloud Builder ツール (リリース バージョン 5.2.x より前) を使用してデプロイされている場合は、vSAN のみがサポートされます。

既存のvSphere環境の使用に関する詳細については、 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["既存の vSphere 環境を管理ドメインに変換する"]詳細については。



=== 管理ドメイン - 追加クラスター

管理ドメイン上の追加の vSphere クラスタは、次のオプションを使用して展開できます。

* vSphere 環境に追加のクラスターを用意し、VCF ブラウンフィールド インポート ツールを使用して vSphere 環境を管理ドメインに変換します。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["ONTAP tools for VMware vSphere"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["システムマネージャまたはONTAP API"] VMFS データストアを vSphere クラスタにデプロイするために使用できます。
* SDDC API を使用して追加のクラスターを展開します。 vSphere ホストには VMFS データストアが設定されている必要があります。使用 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["システムマネージャまたはONTAP API"]LUN を vSphere ホストに展開します。
* SDDC Manager UI を使用して追加のクラスターを展開します。ただし、このオプションはバージョン 5.2.x までの VSAN データストアのみを作成します。




== 追加情報

ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCFの設定方法については、以下を参照してください。link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation ドキュメント"] 。
