---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: vSphere クラスターを NetApp ONTAP NFS データストアで VMware Cloud Foundation 管理ドメインに統合するための要件を確認します。 
---
= NFS データストアを使用して vCenter サーバーインスタンスを VCF 管理ドメインに収束させるための導入要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vSphere クラスターを NetApp ONTAP NFS データストアで VMware Cloud Foundation 管理ドメインに統合するための要件を確認します。

コンバージェンス プロセスには、AFFまたはAFXストレージ システム、NFSトラフィック用のSVMとLIF、スイッチ上のNFS VLAN、vSphereホストとvCenterを備えたvSphereクラスター、およびvMotion用の専用ネットワーク セグメントが必要です。



[[infrastructure-requirements]]
== インフラストラクチャ要件

次のコンポーネントと構成が適切であることを確認してください。

* NetApp AFF または AFX ストレージシステム（NFS トラフィックを許可するように構成されたストレージ仮想マシン（SVM）を備えたもの）。
* NFS トラフィックを伝送するために IP ネットワーク上に作成され、SVM に関連付けられた論理インターフェイス (LIF)。
* 少なくとも2台のvSphereホストと、クラスター上に同じ場所に配置されたvCenterアプライアンスで構成されるvSphereクラスター。
* この目的のために確立された VLAN またはネットワーク セグメント上の vMotion および NFS ストレージ トラフィック用に構成された分散ポート グループ。
* VCF管理ドメインにvCenterを統合するためのVCFインストーラーツール。
* ONTAPツールの前提条件。
+
ONTAPツールの前提条件の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["ONTAP tools for VMware vSphereの前提条件"] 。

+
ONTAP tools for VMware vSphereは、 HA 構成または非 HA 構成のいずれにもインストールできます。





[[additional-resources]]
== その他のリソース

* サポートされているストレージと、vSphere を VCF に収束させる際のその他の考慮事項については、 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["VCFへの収束におけるサポート対象構成とサポート対象外構成"]を参照してください。
* ONTAPストレージシステムの設定については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9 ドキュメント"] 。
* VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 9.1 ドキュメント"]を参照してください。




[[whats-next]]
== 次の手順

展開要件を確認した後、link:vmw-vcf-mgmt-nfs-deploy.html["ONTAPツールを導入し、NFSデータストアをプロビジョニングする"] 。
