---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= ONTAP上のNFSデータストアをVCF管理ドメインの主ストレージとして使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このユースケースでは、VMware Cloud Foundation （VCF）管理ドメインのプライマリストレージとして、ONTAP 上に NFS データストアを作成する手順を概説します。この手順では、必要なコンポーネント、構成手順、および展開プロセスについて説明します。



[[introduction]]
== はじめに

必要に応じて、vCenterで実行する必要がある手順については外部ドキュメントを参照し、ストレージ構成部分に特有の手順については該当箇所を参照してください。

NFS 4.1データストアをプリンシパルストレージとして使用する必要がある場合、またはONTAPを使用する既存のNFSベースのvSphere環境を変換する場合は、link:vmw-vcf-mgmt-nfs.html["vSphere環境（NFSデータストア）をVCF管理ドメインに統合する"]を参照してください。


NOTE: VCF リリース 5.2 では、既存のvSphere 8 環境を VCF 管理ドメインに変換するか、VCF VI ワークロード ドメインとしてインポートする機能が導入されました。今回のリリース以前は、VCF 管理ドメインのプリンシパル ストレージとして利用できるのは VMware vSAN のみでした。NSX コントローラー VM は、FC ベースの VMFS データストアにデプロイするか、デュアル ネットワーク スイッチを使用して単一障害点を回避することをお勧めします。これらのオプションが利用できない場合は、vSAN を使用してそれらの VM をホストすることを検討してください。


NOTE: このソリューションは、NFSストレージをサポートするONTAPプラットフォーム（NetApp AFF、AFX、FASを含む）に適用できます。



[[prerequisites]]
== 前提条件

このシナリオでは、次のコンポーネントと構成が使用されます。

* NFS トラフィックを許可するように構成されたストレージ仮想マシン (SVM) を備えたNetAppストレージ システム。
* NFS トラフィックを伝送し、SVM に関連付けられた IP ネットワーク上に論理インターフェイス (LIF) が作成されています。
* 少なくとも 2 つの vSphere ホストを含む vSphere クラスター。
* 管理ドメインで使用されるものと同じ NFSサーバおよびエクスポートパスを持つ NFS データストアが、いずれかの vSphere ホストにマウントされています。



NOTE: VCF ドメインをデプロイする際、VCF は NFSサーバへの接続性を検証します。これは、NFS IP アドレスを持つ追加の vmkernel アダプタが追加される前に、vSphere ホスト上の管理アダプタを使用して行われます。したがって、検証を続行できるようにするには、1） 管理ネットワークが NFSサーバにルーティング可能であること、または 2） NFS データストア ボリュームをホストする SVM に管理ネットワーク用の LIF が追加されていることを確認する必要があります。

* ONTAP NFS VAAIツールが、クラスタイメージのテンプレートとして選択できるvSphereホストのいずれかにインストールされていることを確認してください。
* VCFインストーラーツールをデプロイします。


ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation ドキュメント"]を参照してください。



[[deployment-steps]]
== 展開手順



[[management-domain-default-cluster]]
=== 管理ドメイン - デフォルトクラスタ

VCFインストーラーツールは、管理ドメインにおいて、FC上のVMFS、NFS v3、およびvSANデータストアをサポートします。以下の手順は、主要なストレージとしてONTAP上のNFSv3ベースのデータストアを使用して管理ドメインをデプロイする手順の概要を示しています。


NOTE: デプロイ後に NFS データストアの nConnect 値を検証または調整します。

既存のvSphere環境の使用方法については、link:vmw-vcf-mgmt-nfs.html["vSphere環境（NFSデータストア）をVCF管理ドメインに統合する"]を参照してください。



[[management-domain-additional-cluster]]
=== 管理ドメイン - 追加クラスター

管理ドメインにクラスターを追加するには、 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["SDDCクラスタをVCFドメインに追加する"]を参照してください。

大まかに言うと、管理ドメインにクラスターを追加する手順は次のとおりです。* ホストがコミッショニングされ、ネットワーク プールが vCenter で構成されていることを確認します。* NFS データストア ボリュームは、ONTAP ストレージ システムにプロビジョニングされ、追加クラスター内のホストにエクスポートされます。* vCenter の管理ドメインに新しい SDDC クラスターを作成し、ウィザードに従って追加のクラスターを管理ドメインに追加します。



[[additional-information]]
== 追加情報

ONTAPストレージシステムの構成については、link:https://docs.netapp.com/us-en/ontap["ONTAP 9ドキュメント"]中心。

VCF の設定方法については、link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation ドキュメント"]を参照してください。
