---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-automation.html 
keywords:  
summary:  
---
= 管理のためのONTAPおよび VMware API の使用について学習します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPと VMware は、ストレージと仮想化プラットフォーム間のシームレスな統合と自動化を実現する API を提供します。これにより、プロビジョニング、監視、データ保護が合理化され、ワークフローの一貫性が向上します。



== はじめに

VMware は、管理者がさまざまな VMware 製品およびサービスとプログラム的に対話し、運用の効率と一貫性を向上できるようにするさまざまな API を提供します。さらに、 NetApp ONTAP API は、特に VMware ワークロードと組み合わせて、管理者がストレージ環境の管理を自動化、統合、最適化できるようにする強力なツール セットを提供します。これらの API により、 ONTAPストレージ システムと VMware 間のシームレスな相互作用が促進され、効率、パフォーマンス、データ保護が向上します。



== VMwareベースのAPI

* *VMware vSphere API:* vSphere API は、管理者が VMware vSphere 環境を管理および自動化できるようにする包括的な API です。仮想マシンのプロビジョニング、構成、監視、ライフサイクル管理など、vSphere の幅広い機能へのアクセスを提供します。
* *VMware vCenter Server REST API:* vCenter Server REST API は、vCenter Server とその関連コンポーネントを管理するための最新の RESTful インターフェイスを提供します。自動化と他のシステムやツールとの統合が簡素化されます。
* *VMware Cloud Foundation API:* VMware Software-Defined Data Center (SDDC) API は、VMware SDDC 環境内のさまざまなコンポーネントとサービスへのプログラムによるアクセスを提供します。これらの API を使用すると、管理者と開発者は、コンピューティング、ストレージ、ネットワーク、管理サービスなど、データセンターのさまざまな側面を自動化、管理、統合できます。
* *VMware vSphere ストレージ API - ストレージ認識:* VASA は、管理および運営のためにストレージ アレイと vCenter の統合を提供する API セットです。アーキテクチャは、VMware vSphere とストレージ システム間の通信を処理する VASA プロバイダーを含む複数のコンポーネントに基づいています。ONTAPでは、プロバイダはONTAP Tools for VMware vSphereの一部として実装されます。
* *VMware vSphere ストレージ API - アレイ統合:* VAAI は、VMware vSphere ESXi ホストとストレージ デバイス間の通信を可能にする API セットです。このAPIには、ストレージ処理をアレイにオフロードするためにホストが使用する一連の基本処理が含まれています。VAAIは、ストレージを大量に消費するタスクのパフォーマンスを大幅に向上させることができます。




== ONTAPベースの API

* * NetApp ONTAP REST API:* ONTAP REST API は、 ONTAPストレージ システムを管理するための最新の RESTful インターフェイスを提供します。プロビジョニング、監視、構成などのストレージ タスクの自動化を簡素化します。 VMware vSphere やその他の VMware 管理ツールとの簡単な統合が可能になり、VMware 環境から直接ストレージ操作を自動化できるようになります。基本的なストレージ管理から高度なデータ保護やレプリケーション タスクまで、幅広い操作をサポートし、スケーラブルで柔軟なストレージ管理を実現します。
* * VMware vSphere 用ONTAPツール:* ONTAP tools for VMware vSphereは、 ONTAPと vSphere を統合するためのツール セットです。VASA APIフレームワークのプロバイダ機能を実装します。ONTAP Toolsには、vCenterプラグイン、VMware Site Recovery Manager用のStorage Replication Adapter（SRA）、自動化アプリケーションの構築に使用できるREST APIサーバも含まれています。




== まとめ

要約すると、 ONTAP API を使用すると、管理者は VMware 環境でのデータストアの作成と構成をスクリプト化できるため、迅速かつ一貫したストレージ プロビジョニングが可能になります。さらに、VMware 仮想マシンのスナップショットの作成、スケジュール設定、削除を自動化できるため、効率的なデータ保護とリカバリのオプションが提供されます。 SnapMirror API は、レプリケーション関係のセットアップと管理の自動化を容易にし、VMware ワークロードに対する堅牢な災害復旧ソリューションを保証します。管理者は、ストレージ パフォーマンス メトリックを監視し、パフォーマンスしきい値を超えたときにアラートまたは自動アクションをトリガーするスクリプトを実装して、VMware ワークロードに最適なストレージ パフォーマンスを確保することもできます。  ONTAP API を vSphere や vRealize などが提供する VMware API と統合することで、管理者はシームレスで高度に自動化された管理エクスペリエンスを実現し、仮想化インフラストラクチャ全体の効率と信頼性を向上させることができます。
