---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= ONTAP tools for VMware vSphereを使用して仮想マシンを管理する方法について学習します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereは、NetAppストレージを使用するVMのライフサイクル管理を効率化します。管理者はvCenter Serverから直接ストレージを管理できるため、運用が簡素化され、拡張性が向上します。vSphere Clientプラグイン、VASA Provider、Storage Replication Adapter（SRA）などの主要コンポーネントにより、プロビジョニング、パフォーマンス監視、ディザスタリカバリが最適化されます。



[[introduction]]
== はじめに

これにより、管理者は vCenter Server 内のストレージを直接管理し、VMware 環境のストレージとデータ管理を簡素化できます。 VMware vSphere Client プラグイン ツールは、vCenter Server 内で実行する必要なく、プラグイン機能を vSphere Client に統合するように設計されています。これにより、プラグインの分離が容易になり、大規模なvSphere環境で動作するプラグインのスケールアウトが実現します。



[[ontap-tools-components]]
== ONTAPツールコンポーネント

* *vSphere Clientプラグイン* このプラグインには、vSphere Clientと統合されたインターフェイスが含まれており、ストレージコントローラの追加、データストアのプロビジョニング、データストアのパフォーマンス監視、ESXiホスト設定の表示と更新を行うことができます。ONTAP tools 9.xでは、このコンポーネントはVirtual Storage Console（VSC）と呼ばれます。
* *VASA プロバイダー* ONTAP用の VMware vSphere APIs for Storage Awareness (VASA) プロバイダーは、VMware vSphere が使用するストレージに関する情報を vCenter Server に送信し、VMware Virtual Volumes (vVols) データストアのプロビジョニング、ストレージ機能プロファイルの作成と使用、コンプライアンス検証、およびパフォーマンス監視を可能にします。
* *ストレージ レプリケーション アダプタ (SRA)* SRA を有効にして VMware Site Recovery Manager (SRM) と併用すると、障害発生時に vCenter Server データストアと仮想マシンのリカバリが容易になり、災害復旧用の保護サイトとリカバリ サイトを構成できるようになります。


詳細については、ご使用のバージョンのONTAP tools for VMware vSphereのドキュメントを参照してください：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["ONTAP tools for VMware vSphere 10.x ドキュメント"^]（最新リリース）
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP tools for VMware vSphere 9.x ドキュメント"^]

