---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security.html 
keywords:  
summary:  
---
= VMware ワークロードのセキュリティとランサムウェアのリスクを軽減する方法について学習します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP は、暗号化、スナップショット、高度なアクセス制御を通じて VMware 環境のセキュリティとランサムウェア保護を強化し、VMware のセキュリティ機能を補完してデータを保護します。



== はじめに

VMware 環境内でNetApp ONTAPの高度な機能を活用することで、組織はデータの整合性、可用性、セキュリティを確保できます。

これらのテクノロジーがどのように連携して*セキュリティ*と*バックアップのメリット*を実現するかの詳細については、以下を参照してください。



== セキュリティとランサムウェア

セキュリティは仮想化環境における最も重要な懸念事項であり、 NetApp ONTAP はVMware インフラストラクチャ内のセキュリティを強化する強力な機能を提供します。 ONTAP は、保存中のデータと転送中のデータの暗号化を提供し、機密情報が不正アクセスから保護されることを保証します。暗号化キーは安全に管理され、 ONTAP はソフトウェアベースとハードウェアベースの両方の暗号化ソリューションをサポートします。  ONTAP は、vSphere の組み込みセキュリティ機能やサードパーティのセキュリティ ソリューションなどの VMware のセキュリティ ツールと統合することで、安全でコンプライアンスに準拠した環境の構築に役立ちます。



== ランサムウェア対策

ランサムウェア攻撃は組織にとって重大な脅威であり、VMware とONTAPを組み合わせることで強力な防御メカニズムが実現します。 ONTAP のスナップショット テクノロジーにより、ランサムウェアによって変更または削除されない不変のスナップショットを作成できます。攻撃が発生した場合、これらのスナップショットを使用すると、影響を受けた VM とデータストアを攻撃前の状態に迅速に復元し、ダウンタイムとデータ損失を最小限に抑えることができます。さらに、ONTAP とセキュリティ情報イベント管理 (SIEM) システムの統合により、疑わしいアクティビティをプロアクティブに監視して警告することが可能になります。  ONTAP は、セキュリティをさらに強化するために、多要素認証 (MFA) とロールベース アクセス制御 (RBAC) もサポートしています。



== ランサムウェア リカバリ保証

NetApp Ransomware Guarantee は、ランサムウェア攻撃から保護するための堅牢で信頼性の高いソリューションを組織に提供します。 NetApp ONTAPの高度な機能を活用することで、組織はデータのセキュリティと可用性を確保できます。この保証により、ランサムウェア攻撃が発生した場合でも、データが迅速かつ効果的に復元され、ダウンタイム、データ損失、経済的影響が最小限に抑えられることがわかり、安心できます。データ セキュリティと復元力に対するこの取り組みにより、 NetApp は進化するサイバー脅威から重要な資産を保護したい組織にとって理想的なパートナーとなります。



== 高度なセキュリティ機能

ONTAP には、マルチテナント環境でデータとリソースを分離するセキュア マルチテナントや、機密データへのアクセスを追跡して記録するコンプライアンス監査などの高度なセキュリティ機能が含まれています。これらの機能により、データの安全性が確保され、組織は業界の規制や標準への準拠を実証できます。



== まとめ

暗号化、不変のスナップショット、高度なアクセス制御などの ONTAP のセキュリティ機能を VMware のツールと統合することで、ランサムウェアなどのサイバー脅威に対する強力な防御を実現します。  ONTAP は安全なマルチテナントとコンプライアンス監査をサポートしており、データ保護と規制コンプライアンスを保証します。

NetApp ONTAPと VMware を組み合わせることで、仮想化環境のセキュリティを確保するための包括的なソリューションが提供され、組織はデータを保護し、ダウンタイムを最小限に抑え、ビジネスの継続性を維持できるようになります。これらのテクノロジーを実装することで、企業は現代の IT の課題に対処し、進化するセキュリティの脅威から重要な資産を保護することができます。
