---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= VMware vSphere Metro Storage Cluster を使用して、SM アクティブ同期を非対称から対称アクティブ/アクティブに変換する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この記事では、VMware vSphere Metro Storage Cluster (VMSC) を使用して、 SnapMirrorアクティブ同期を非対称から対称アクティブ/アクティブに変換する方法について詳しく説明します。



== 概要

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["NetApp Snapmirror アクティブ同期 (SM アクティブ同期)"]仮想化環境でゼロ復旧時間目標 (RTO) とゼロ復旧ポイント目標 (RPO) を達成するための堅牢なソリューションです。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["VMware vSphere メトロ ストレージ クラスタ (vMSC)"]は、異なる障害ドメインにまたがるストレッチ クラスタ ソリューションであり、仮想マシン (VM) を地理的に離れた 2 つのサイトに分散して、1 つのサイトに障害が発生しても継続的な可用性を実現できます。

vMSC と SM Active Sync を組み合わせることで、2 つのサイト間のデータの一貫性と即時フェイルオーバー機能が確保されます。この設定は、データの損失やダウンタイムが許容されないミッションクリティカルなアプリケーションにとって特に重要です。

SM アクティブ シンク (以前はSnapMirror Business Continuity (SMBC) と呼ばれていました) により、サイト全体の障害が発生してもビジネス サービスの運用が継続できるようになり、セカンダリ コピーを使用してアプリケーションが透過的にフェイルオーバーできるようになります。 ONTAP 9.15.1 以降、SM アクティブ同期は対称アクティブ/アクティブ機能をサポートします。対称アクティブ/アクティブでは、双方向同期レプリケーションを使用して、保護された LUN の両方のコピーからの読み取りおよび書き込み I/O 操作が可能になり、両方の LUN コピーがローカルで I/O 操作を処理できるようになります。

このドキュメントでは、VMware ストレッチ クラスタ環境で SM アクティブ同期非対称アクティブ/アクティブを SM アクティブ同期対称アクティブ/アクティブに変換する手順、つまり、SM アクティブ同期を自動フェイルオーバー ポリシーから自動フェイルオーバー デュプレックス ポリシーに変換する手順について説明します。  System ManagerとONTAPツールを使用してSnapMirror Active Sync（SM-as）でvMSCを設定する方法の詳細については、link:vmw-vmsc-with-smas.html["SnapMirrorアクティブ同期を備えた VMware vSphere Metro Storage Cluster"] 。



== 前提条件

* NetAppストレージ システム: Snapmirror ライセンスを持つ 2 つのNetAppストレージ クラスター (ソースと宛先) があることを確認します。
* ネットワーク接続: ソース システムと宛先システム間の低遅延ネットワーク接続を確認します。
* クラスターと SVM ピアリング: ソース クラスターと宛先クラスター間のクラスター ピアリングとストレージ仮想マシン (SVM) ピアリングを設定します。
* ONTAPバージョン: 両方のクラスターが同期レプリケーションをサポートするONTAPのバージョンを実行していることを確認します。  SM アクティブ同期には、 ONTAP 9.15.1 以降が必要です。
* VMware vMSC インフラストラクチャ: ストレッチ クラスタによりサブシステムを地理的に分散させることが可能になり、両方のサイトの vSphere クラスタに単一の共通の基本インフラストラクチャ リソース セットが提供されます。サイト間のネットワークとストレージを拡張します。
* NetApp SnapMirrorの使いやすさのためにONTAPツール10.2以降を使用してください。詳細については、link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["ONTAP tools for VMware vSphere。"]
* プライマリ クラスターとセカンダリ クラスターの間には、ゼロ RPO Snapmirror 同期関係が存在する必要があります。
* ゼロ RTO Snapmirror 関係を作成する前に、宛先ボリューム上のすべての LUN をマップ解除する必要があります。
* Snapmirror Active Sync は SAN プロトコルのみをサポートします (NFS/CIFS はサポートしません)。NASアクセス用に整合性グループのコンスティチュエントがマウントされていないことを確認します。




== 非対称SMアクティブ同期から対称SMアクティブ同期に変換する手順

以下の例では、selectrz1 がプライマリ サイトであり、selectrz2 がセカンダリ サイトです。

. セカンダリ サイトから、既存の関係に対してSnapMirror更新を実行します。
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. SnapMirror の更新が正常に完了したことを確認します。
+
....
selectrz2::> snapmirror show
....
. ゼロ RPO 同期関係をそれぞれ一時停止します。
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. ゼロ RPO 同期関係をそれぞれ削除します。
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. ソースSnapMirror関係を解除しますが、共通スナップショットは保持します。
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. AutomatedFailoverDuplex ポリシーを使用して、ゼロ RTO SnapMirror同期関係を作成します。
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. 既存のホストがプライマリ クラスタに対してローカルである場合は、ホストをセカンダリ クラスタに追加し、各クラスタにそれぞれアクセスできるよう接続を確立します。
. セカンダリ サイトで、リモート ホストに関連付けられているigroupのLUNマップを削除します。
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. プライマリ サイトで、既存のホストのイニシエータ設定を変更して、ローカル クラスタのイニシエータの近接パスを設定します。
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. 新しいホスト用の新しいigroupとイニシエータを追加し、ホストの近接性を設定してローカル サイトに対するホスト アフィニティを確立します。igroup レプリケーションを有効にして構成を複製し、リモート クラスター上のホストの局所性を反転します。
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. ホスト上のパスを検出し、優先クラスターからストレージ LUN へのアクティブ/最適化されたパスがホストにあることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散します。
. 整合性グループを再同期します。
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. ホストのLUN I/Oパスを再スキャンして、LUNへのすべてのパスをリストアします。

