---
sidebar: sidebar 
permalink: videos/hybrid-cloud-videos.html 
summary: NetAppによるハイブリッド クラウド仮想化ソリューションを紹介するビデオとデモ 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= NetAppによるハイブリッドマルチクラウド仮想化に関するビデオを見る
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp が主要なハイブリッド マルチクラウド プラットフォーム全体でハイブリッド クラウド仮想化を実現する方法をご覧ください。仮想化ワークロード向けの FSx ONTAPおよびNetApp HCIソリューションを使用した Red Hat OpenShift Service on AWS (ROSA) のデモビデオをご覧ください。



== FSx ONTAPを使用した AWS 上の Red Hat OpenShift サービス (ROSA)

.ホスト型コントロールプレーンを使用した AWS 上の Red Hat OpenShift サービスとAmazon FSx for NetApp ONTAP
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.FSx ONTAPとTridentの統合
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.Amazon FSx ONTAPストレージを使用した Red Hat OpenShift Service on AWS (ROSA) クラスター上のアプリケーションのスナップショット/リストア
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.FSx ONTAPを使用した ROSA 上のアプリのフェイルオーバーとフェイルバック
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]


== NetApp HCIソリューション

.Red Hat Virtualization 上の Red Hat OpenShift 向けNetApp HCI
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]