---
sidebar: sidebar 
permalink: videos/openshift-videos.html 
summary: OpenShift VirtualizationとNetAppストレージソリューションの統合を紹介するビデオとデモ 
keywords: openshift, virtualization, netapp, trident, videos, demos 
---
= NetAppを使用した Red Hat OpenShift 仮想化に関するビデオを見る
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ディザスタリカバリ、VM 保護、ストレージ管理、 Tridentと Ansible を使用した自動化などの主要な機能を紹介する一連のビデオを通じて、OpenShift Virtualization とNetAppの統合について詳しく説明します。



== VMの管理と運用

.iSCSI ストレージを使用して OpenShift Virtualization で VM を作成する
video::497b868d-2917-4824-bbaa-b2d500f92dda[panopto,width=360]
.OpenShift Virtualization を使用した仮想マシンの導入 - Red Hat OpenShift とNetApp
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.Amazon FSx for NetApp ONTAPを使用した ROSA 上の OpenShift Virtualization における仮想マシンのライブマイグレーション
video::4b3ef03d-7d65-4637-9dab-b21301371d7d[panopto,width=360]
.Red Hat MTV を使用して、 NetApp ONTAPストレージを搭載した OpenShift Virtualization に VM を移行する
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.ワークロード移行 - Red Hat OpenShift とNetApp
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]


== データ保護とディザスタ リカバリ

.Trident Protectを使用したVMの保護
video::4670e188-3d67-4207-84c5-b2d500f934a0[panopto,width=360]
.Trident Protectを使用したVMのディザスタリカバリ
video::ae4bdcf7-b344-4f19-89ed-b2d500f94efd[panopto,width=360]
.Tridentの高度なデータ管理機能を使用した OpenShift VM のフェイルオーバー/フェイルバック (早期アクセス プログラムのみ利用可能)
video::f2a8fa24-2971-4cdc-9bbb-b1f1007032ea[panopto,width=360]


== ストレージの統合と管理

.Red Hat 認定Tridentオペレーターを使用してTridentをインストールする
video::15c225f3-13ef-41ba-b255-b2d500f927c0[panopto,width=360]
.ONTAP SAN (iSCSI) ストレージクラスを使用して OpenShift Virtualization に新しい VM をデプロイする
video::2e2c6fdb-4651-46dd-b028-b1ed00d37da3[panopto,width=360]
.ONTAP NASストレージクラスを使用してPostgreSQLコンテナアプリをデプロイする
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]


== 自動化と監視

.Ansible 自動化によるTrident のデプロイと OpenShift クラスターへのストレージ クラスの作成
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
link:https://github.com/NetApp/trident-install["Ansible を使用してNetApp Trident、StorageClasses、および Backend をインストールするために使用するプレイブックは、github にあります。"]

.Cloud InsightsとOpenshift Virtualizationの統合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.OpenShift Virtualization のインストール - Red Hat OpenShift とNetApp
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]