---
sidebar: sidebar 
permalink: opennebula/opennebula-storage-types.html 
keywords: netapp, opennebula, ontap, storage, nfs, smb, cifs, iscsi, fc, nvme, content types, vm disks, backups, templates 
summary: OpenNebulaは、NASプロトコル用のNFSおよびSMB、SANプロトコル用のFC、iSCSI、NVMe-oFなど、ONTAPを使用した複数のストレージタイプをサポートしています。 
---
= OpenNebulaでサポートされているストレージタイプ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
OpenNebulaは、NetApp ONTAPで複数のストレージ プロトコルをサポートしています。NAS用のNFSおよびSMB、SAN用のFC、iSCSI、NVMe-oFなどが含まれます。既存のスキルセットと要件に基づいて、ユーザーは適切なストレージ プロトコルを選択できます。ONTAPが提供するデータサービスを使用する予定がない場合は、FC、iSCSI、Infiniband、NVMe-oFプロトコルを使用してブロック ストレージを提供できるSANtricityシステムを検討してください。

OpenNebulaは、通常、/var/lib/one/datastores フォルダにマウントされるか、/etc/one/oned.conf ファイルの DATASTORE_LOCATION 属性で定義されているデータストアを使用します。ストレージは、/etc/fstab ファイルを使用してマウントすることも、Automounter または環境でサポートされているその他の手順を使用して動的にマウントすることもできます。フォルダの権限のほとんどは、oneadmin ユーザとグループによって所有されるように設定されています。ハイパーバイザーホストが必要なプロトコルを使用してストレージ システムにアクセスできることを確認してください。

自動マウント機能を使用する場合は、自動マウント機能が親フォルダーを制御する問題を回避するために、直接マウントを使用します。直接マウントを作成するには、/etc/auto.master.d/ の下にファイルを作成します。たとえば、次のコマンドで one.autofs という名前のファイルを作成します：

[source, bash]
----
echo "/-    /etc/auto.one --timeout=60 --ghost" > /etc/auto.master.d/one.autofs
----
フロントエンド サーバーはイメージ データストアにアクセスできる必要があります。ハイパーバイザー ホストへのイメージ データストアのマウントはオプションですが、パフォーマンス向上のために推奨されます。システム データストアは、仮想マシン ディスクをホストするため、ハイパーバイザー ホストにマウントする必要があります。カーネルおよびファイル データストアは、コンテキスト化プロセスを通じて VM に必要な VM カーネル、RAM ディスク、およびその他のファイルに使用されます。フロントエンド サーバーとハイパーバイザー ホストの両方にマウントできます。バックアップ データストアは VM バックアップに使用され、OpenNebula クラスタのすべてのホストにマウントできます。KVM ホストが rsync の場合は SSH、restic の場合は SFTP を使用してバックアップ データストア ホストにアクセスできる場合、他のクラスター上の VM も同じバックアップ データストアを使用できます。Veeam を使用する場合は、oVirtAPI が利用可能である必要があります。



== NASプロトコルのサポート

NASプロトコル（NFSおよびSMB）は、フロントエンドとハイパーバイザーホスト全体で共有ファイルシステムをサポートします。ONTAPスナップショットをクライアントに公開して、ポイントインタイムデータのコピーにアクセスできるようにすることができます。ONTAP FlexCacheは、地理的に分散されたゾーン内のイメージデータストアに使用できます。ONTAP NFSはnConnectをサポートしており、セッションごとに複数の接続を使用することでパフォーマンスが向上します。大規模なデータストア（> 100TB）にFlexGroupを使用する場合、複数のノードに負荷を分散するためにpNFSが推奨されます。ONTAPクラスター内のコントローラごとに少なくとも1つのデータLIFを構成し、ハイパーバイザーホストが接続されている必要があることを忘れないでください。

すべてのデータストア タイプ（イメージ、システム、カーネルとファイル、バックアップ）は NAS プロトコルをサポートしています。



== SANプロトコルのサポート

Enterprise edition には、AFF および FAS システムで iSCSI プロトコルを使用する NetApp ドライバーが含まれています。その他の SAN プロトコル（FC、InfiniBand、NVMe-oF）は、通常 LVM ドライバー用に構成されます。LVM シン プールは、シンプロビジョニングおよびスナップショット対応のために仮想マシンごとに作成されます。ハイパーバイザー ホストはストレージ システムへの接続が必要です。LVM ストレージ タイプを使用するために Cluster LVM サポートは必要ありません。

NetAppドライバを使用するには、ハイパーバイザーホストでiSCSIセッションとマルチパスを設定する必要があります。LVMドライバの場合、システムデータストアを除き、論理ボリュームにファイルシステムを作成してマウントする必要があります。システムデータストアの場合、ボリュームグループは「vg-one-<datastore_id>」という名前にする必要があります。ここで、<datastore_id>はOpenNebulaのデータストアの数値識別子です。すべてのデータストアタイプ（イメージ、システム、カーネルとファイル、バックアップ）はSANプロトコルをサポートしています。



== NetApp ONTAP API ドライバー

OpenNebulaのネイティブNetApp統合では、ONTAPのAPIを使用して、ボリューム、LUN、スナップショット、マッピングを自動的に作成および管理します。この方法は最高レベルの自動化を提供し、手動によるiSCSIおよびLVMのセットアップを回避します。link:https://docs.opennebula.io/7.0/integrations/storage_extensions/netapp/["OpenNebulaドキュメント"]詳細については、こちらを参照してください。



== ストレージタイプの互換性マトリックス

[cols="25% 15% 15% 15% 15% 15%"]
|===
| データストアのタイプ | NFS | SMB / CIFS | FC | iSCSI | NVMe-oF 


| イメージ | はい | はい | はい  a| 
はい^1^
| はい 


| システム | はい | はい | はい  a| 
はい^1^
| はい 


| カーネルとファイル | はい | はい | はい | はい | はい 


| バックアップ | はい | はい | はい | はい | はい 
|===
*注記:*

. NetAppドライバは、ネイティブONTAP機能を利用するために、iSCSIプロトコル用のEnterpriseエディションで利用できます。




== OpenNebula クラスタストレージタイプは ONTAP でサポートされています

NetApp ONTAPをバックエンドとして使用する場合の、OpenNebulaにおける異なるストレージタイプでサポートされている機能の比較を以下に示します。

[cols="30% 20% 20% 20%"]
|===
| 機能 | NetApp ONTAP API | LVM-thin | NFS / SMB 


| VMディスク | はい | はい | はい 


| 画像ストレージ^1^ | はい | はい | はい 


| ライブスナップショット | はい | はい | はい 


| VMまたはイメージのクローン | はい | はい | はい 


| 増分バックアップ^2^ | はい | はい | はい 
|===
*注記:*

. 画像ストレージとは、OpenNebulaイメージデータストアのバックエンドを使用することを指します。LVM-thinとONTAP APIメソッドには、イメージソースからのブロックデバイスのコピーまたは作成が含まれます。
. 増分バックアップは、 `qcow2`ディスク（NFS/SMB上）または変更追跡をサポートするブロックデバイスで動作します。OpenNebula NetApp ONTAPドライバーは、ロールリングスナップショットを使用して増分バックアップを作成します。



NOTE: 増分バックアップには `nbd`カーネル モジュールをロードする必要があります。
